name: github-actions-sample
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest tests
  build-and-push:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: "arn:aws:iam::${{secret.AWS_ACCOUNT}}:role/${{secret.SECRET_ROLE}}"
      - name: Docker build and push
        run: |
          docker build -t github-actions-sample .
          docker tag github-actions-sample:latest ${{secret.AWS_ACCOUNT}}.dkr.ecr.ap-northeast-1.amazonaws.com/github-actions-sample:latest
          docker push ${{secret.AWS_ACCOUNT}}.dkr.ecr.ap-northeast-1.amazonaws.com/github-actions-sample:latest
